#!/usr/bin/env python3
"""Generate AGENTS.md for a repository based on its structure."""

import os
import sys
import json
import subprocess

def generate(root="."):
    # Run analysis
    result = subprocess.run(
        ["python", os.path.join(os.path.dirname(__file__), "analyze_repo.py"), root],
        capture_output=True, text=True
    )
    data = json.loads(result.stdout)

    top_dirs = data.get("top_level_dirs", [])
    stack = data.get("stack", [])
    key_files = data.get("key_files", [])

    # Build directory tree section
    tree_lines = []
    ignored = {".git", "node_modules", "__pycache__", ".next", "dist", "build", "venv", ".venv"}
    for d in sorted(top_dirs):
        if d not in ignored:
            tree_lines.append(f"├── {d}/")
    for f in sorted(key_files):
        tree_lines.append(f"├── {f}")
    tree = "\n".join(tree_lines)

    stack_str = ", ".join(stack) if stack else "Unknown"

    content = f"""# AGENTS.md

> Auto-generated by agents-md-gen skill. Update as the codebase evolves.

## Repository Overview

This repository is part of the LearnFlow AI-powered Python tutoring platform.

## Tech Stack

{stack_str}

## Directory Structure

```
{os.path.basename(os.path.abspath(root))}/
{tree}
```

## Conventions

- Follow existing code style in each service
- All backend services use FastAPI (Python)
- Dapr annotations required on all K8s service deployments
- Kafka topics follow pattern: `<domain>.<event>` (e.g., `learning.started`)
- Scripts in `.claude/skills/*/scripts/` are executed, never loaded into context

## Key Commands

```bash
# Run a service locally
uvicorn main:app --reload

# Apply K8s manifests
kubectl apply -f k8s/

# Check all pods
kubectl get pods -A
```

## AI Agent Guidelines

- Use skills from `Learnflow-skills` repo to build and deploy components
- Do not write application code manually — use the appropriate skill
- Always verify deployments with the skill's verify script before proceeding
- Commit messages should reference the skill used (e.g., "Claude: deployed Kafka using kafka-k8s-setup skill")
"""

    output_path = os.path.join(root, "AGENTS.md")
    with open(output_path, "w") as f:
        f.write(content)

    print(f"✓ AGENTS.md generated at {output_path}")

if __name__ == "__main__":
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    generate(root)
